# general settings
name: trainS2_8b_64c_keep
model_type: VideoRecurrentModel
scale: 4
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 44

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KRecurrentDataset
    dataroot_gt: /gdata1/gaors/VSRdataset/vimeo_septuplet/sequences
    dataroot_lq: /gdata1/gaors/VSRdataset/vimeo_septuplet_matlabLRx4/sequences
    meta_info_file: basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    io_backend:
      type: disk

    num_frame: -1        # -1 represents using 7 frames
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: true  #true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

  val:
    name: Vid4
    type: VideoRecurrentTestDataset
    dataroot_gt: /gdata1/gaors/VSRdataset/Vid4/GT
    dataroot_lq: /gdata1/gaors/VSRdataset/Vid4/BIx4

    cache_data: True
    io_backend:
      type: disk

    num_frame: -1  # not needed

# network structures
network_g:
  type: DFlow
  num_feat: 64
  num_block: 2
  return_wimage: False

# path
path:
  pretrain_network_g: /gdata1/gaors/DFlow_BasicSR/experiments/pretrained_models/s2_250000.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 6e-6
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 250000
  warmup_iter: -1  # no warm up
  fix_flow: 0  
  flow_lr_mul: 1

  # losses
  pixel_opt:
    #type: CharbonnierLoss
    type: MSELoss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
